### ISSUE TITLE
English UI and configuration dialog

### ISSUE THREAD

**Issue by O-Palda** [klacol/homeassistant-clage_homeserver#1]
### What happened?

The configuration dialog has not been showing what needs to be filled in the 4 entry boxes.

Could I help you with finishing English translation of this integration? I was able to integrate it and utilise only after going through German version of what the configuration dialog should look like.  

I do not have many programming experiences, but if you could point me at what needs to be translated and or finished in English from German source file, I can push a request.

Thank you very much for the integration, I have been looking  for it for more than a year :) 

### Version

latest

### What version of Home Assistant are you seeing the problem on?

 2021.11.5

**Comment by klacol** [comment]
Hi @O-Palda , great to see anybody using this integration. I have corrected the english translation. Please check, if it works for you now.

**Comment by O-Palda** [comment]
The configuration dialog works now :) thank you

**Comment by klacol** [comment]
Ok, feel free to make a PR in your language, if it is not english. You just need to add [this file](https://github.com/klacol/homeassistant-clage_homeserver/blob/master/custom_components/clage_homeserver/translations/en.json) in you language.
