### ISSUE TITLE
[Bug]: Scald protection multiplied by 10

### ISSUE THREAD

**Issue by O-Palda** [klacol/homeassistant-clage_homeserver#2]
### What happened?

sensor.clagehomeserver_bila_koupelna_heater_setup_scaldprotection / Verbrühschutztemperatur  

This sensor shows 400 C, instead of 40 C that is set on the heater as the maximal temperature.

### Version

0.1.0

### What version of Home Assistant are you seeing the problem on?

2021.11.5

**Comment by klacol** [comment]
Ok, this has to be fixed in the underlying [python library](https://pypi.org/project/clage-homeserver/). The source code is [living here](https://github.com/klacol/clage_homeserver).

**Comment by klacol** [comment]
The relevant code [is here](https://github.com/klacol/clage_homeserver/blob/main/clage_homeserver/clage_homeserver.py#L110).

**Comment by klacol** [comment]
I have created a new version for the unerlying python library and referenced the new version in the manifest file of the integration.

```python
"requirements": ["clage-homeserver==0.1.6"]
```

This version should be pulled then on update of this integration, e.g. through [HACS](https://hacs.xyz/docs/faq/custom_repositories), or manually. 

Please try.

**Comment by klacol** [comment]
The reason here is, that in fact the value 400 comes from the API. They transport integer values to be able to have one position after the comma.

400 => 40.0 °C
345 => 34.5 °C

I think, I have forgotten to round the division; but lets see, if it works.

**Comment by O-Palda** [comment]
It works wonderfully, thank you.

**Comment by O-Palda** [comment]
I have tries changing the scalding protection value in the clage smart app and it offers only whole grades of Celsius, and it reflects the same in Hassio

**Comment by klacol** [comment]
> I have tries changing the scalding protection value in the clage smart app and it offers only whole grades of Celsius, and it reflects the same in Hassio

Ok, good to know. Then they only store this internally and allow in the app whole grades of Celsius.
