### ISSUE TITLE
[Bug]: Sensors not updating themselves, error setting up sensors

### ISSUE THREAD

**Issue by O-Palda** [klacol/homeassistant-clage_homeserver#3]
### What happened?

Hello Klaus,

I had a issue with sensor sensor.clagehomeserver_bila_koupelna_consumption_energy which did not update itself, it got loaded when the home assistant has been restarted but then it stayed the same till the restart of Hassio. Then I noticed in logs that there is a problem with another sensors as below:

From 3 energy sensors:

sensor.clagehomeserver_bila_koupelna_heater_status_power - shows actual realtime energy consumption 

sensor.clagehomeserver_bila_koupelna_consumption_energy - gets updated only when hassio is restarted

sensor.clagehomeserver_bila_koupelna_heater_setup_totalpowerconsumption - is unavailable with the error message down below. [In clage smart app the status called total Power/Water consumption is 0.0 kW / litres)

The same is true for the 3 corresponding water sensors.

Also the sensor: sensor.clagehomeserver_bila_koupelna_number_of_watertaps is updated only when hassio is restarted.

I have heater software version DSX3CP-v1.1.11 - which smart app is not letting me update, but I have not yet tried to update it on the heater itself.

Can I try something to help diagnose the issue?

Thank you very much

### Version

latest

### What version of Home Assistant are you seeing the problem on?

2021.11.

### Relevant log output

```shell
Logger: homeassistant
Source: custom_components/clage_homeserver/sensor.py:602
Integration: CLAGE Homeserver (documentation, issues)
First occurred: November 22, 2021, 8:01:48 AM (12802 occurrences)
Last logged: 11:34:11 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/clage_homeserver/sensor.py", line 602, in state
    return self.coordinator.data[self.homeservername][self._attribute]
KeyError: 'heater_setup_totalPowerConsumption'

-----------

Logger: custom_components.clage_homeserver
Source: custom_components/clage_homeserver/__init__.py:129
Integration: CLAGE Homeserver (documentation, issues)
First occurred: November 24, 2021, 7:40:59 AM (73 occurrences)
Last logged: November 24, 2021, 8:10:59 AM

Unexpected error fetching clage_homeserver data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/clage_homeserver/__init__.py", line 129, in fetch_states
    await self._hass.async_add_executor_job(homeserver.requestStatus)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/clage_homeserver/clage_homeserver.py", line 369, in requestStatus
    response = ClageHomeServerMapper().mapApiStatusResponse(status)
  File "/usr/local/lib/python3.9/site-packages/clage_homeserver/clage_homeserver.py", line 29, in mapApiStatusResponse
    heater = status.get('devices')[NUMBER_OF_CONNECTED_HEATERS-1]
TypeError: 'NoneType' object is not subscriptable

----

Logger: homeassistant.components.sensor
Source: custom_components/clage_homeserver/sensor.py:602
Integration: Sensor (documentation, issues)
First occurred: November 22, 2021, 8:01:27 AM (2 occurrences)
Last logged: November 22, 2021, 8:01:27 AM

Error adding entities for domain sensor with platform clage_homeserver
Error while setting up clage_homeserver platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/clage_homeserver/sensor.py", line 602, in state
    return self.coordinator.data[self.homeservername][self._attribute]
KeyError: 'heater_setup_totalPowerConsumption'
```

**Comment by klacol** [comment]
Hi @O-Palda ,

I have the same version of the homeserver. The update via App does not work for me either. An error message, about file access, that I could not solve.

I will have a look and come back later.

**Comment by O-Palda** [comment]
Thank you a lot, sadly I am not a programmer, I tried to access the homeserver through console and utilize "total" parameter as defined in section 3.5 of the documentation that should probably sent only the total consumption without all previous watertaps, but I was not able to sent the parameter right, it always returned all watertaps and it took few seconds (currently we are at 9276 taps), but this parameter could enable faster response from homeserver?

If I looked at the python source code of the library I think that it gets totals by enumeraring all watertaps?

**Comment by klacol** [comment]
I have drafted a new version; we can test it now in HA.

**Comment by O-Palda** [comment]
Hi Klaus,

I have updated the addon and all errors are gone from the log. 

The totals now correspond to the "Last 4 years" statistics in Clage smart app. 

Litres are spot on, energy differs by 0.3 kWh (smart app shows bigger number as 980.3 kWh), I will check it after evening shower how will it change on both.

Thanks a lot :)

**Comment by O-Palda** [comment]
Hi Klaus,

I have tried to create a pull request, but I have failed spectacularly :/ as it has been added as pull request to my fork instead https://github.com/O-Palda/clage_homeserver/pull/1

I have basically increased the precision to two (electricity) and one (water) in totals and removed the final rounding as it seemed to me as redundant.

I can see that today I have consumed 2.48 kW and 87.2 l so these decimals seems better to me for statistical purposes. It also lines nicely with the clage smart app. 


I have modified line 334 and 335:

           consumption_energy = round(int(heater_logs.get('power'))/1000,1)    # power	uint32_t	1/1 Wh	6 Wh	Energy demand in kWh, it is energy(kWh) not power (kW)
            consumption_water = round(int(heater_logs.get('water'))/100,0)      # water	uint32_t	1/100 l	0,42 l	Amount of water used in liters
            consumption_energy = round(int(heater_logs.get('power'))/1000,2)    # power	uint32_t	1/1 Wh	6 Wh	Energy demand in kWh, it is energy(kWh) not power (kW)
            consumption_water = round(int(heater_logs.get('water'))/100,1)      # water	uint32_t	1/100 l	0,42 l	Amount of water used in liters

and 340, 341:

'consumption_energy': round(consumption_energy,0),               # Total energy in kWh
            'consumption_water': round(consumption_water,0),                 # Total water volume in liters
            'consumption_energy': consumption_energy,               # Total energy in kWh
            'consumption_water': consumption_water,                 # Total water volume in liters


Thanks a lot

**Comment by klacol** [comment]
> I have tried to create a pull request, but I have failed spectacularly :/ as it has been added as pull request to my fork instead [O-Palda/clage_homeserver#1](https://github.com/O-Palda/clage_homeserver/pull/1)

You have been almost there. Next time you can try to [compare across forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

I have published the new version `224ffd5`to be tested.

**Comment by O-Palda** [comment]
Hello Klaus,

I have the new version deployed for the last two days and it works splendidly.

Thank you very much

**Comment by klacol** [comment]
Ok, den we can close the issue.
