### ISSUE TITLE
[Bug]: ENTITY_CATEGORY_DEPRECATED

### ISSUE THREAD

**Issue by O-Palda** [klacol/homeassistant-clage_homeserver#6]
### What happened?

Home Assisstant has deprecated ENTITY_CATEGORY constant and replaced it with EntityCategory. enum in sensor.py >

`from homeassistant.const import (
    ENTITY_CATEGORY_CONFIG,
    ENTITY_CATEGORY_DIAGNOSTIC,
)`

I have replaced it with 

`from homeassistant.helpers.entity import EntityCategory`

and then replacing ENTITY_CATEGORY classes with EntityCategory.CONFIG / EntityCategory.DIAGNOSTICT in entity_category= of each sensor and error messages in logs have stopped.

I dont know whether the errors appear before updating to 2022.9.2 of Hassio version with the latest clage_homeserver integration.

Thank you very much,

Ondrej

### Version

latest

### What version of Home Assistant are you seeing the problem on?

2022.9.2

**Comment by klacol** [comment]
Fixed with #7, Thanks
