### ISSUE TITLE
Install via HACS

### ISSUE THREAD

**Issue by Kime203** [klacol/homeassistant-clage_homeserver#9]
### Describe the solution you'd like

Unfortunately, the extension cannot be found at HASC. Of course you can do it manually but I think it would be better if something else.

**Comment by klacol** [comment]
Yes, agreed. But I do not know how.

**Comment by klacol** [comment]
Here is an info: https://hacs.xyz/docs/publish/start/

**Comment by Kime203** [comment]
Hi, I'm afraid I don't quite understand. You wrote in your installation instructions that it should be installed via HACS. But that is not working now. What can I do with the link you published here?

Hallo, ich verstehe das jetzt leider nicht so ganz. Du hast in deiner Installationsanleitung geschrieben, dass man es über HACS installieren soll. Aber das funktioniert jetzt nicht. Was kann ich mit dem Link machen den du hier veröffentlicht hast?

**Comment by klacol** [comment]
Hello @Kime203 , I have prepared the installation via HACS. But, we have to wait now, until this pull request is approved by the maintainers of the HACS-repo: https://github.com/hacs/default/pull/1673

**Comment by klacol** [comment]
Ok, done
